### ISSUE TITLE
Unable to upload artist profile and music

### ISSUE THREAD

**Issue by NFTPugs** [INFLOWMusic/inflow-app#150]
<img width="1272" alt="Screen Shot 2022-01-25 at 6 17 31 PM" src="https://user-images.githubusercontent.com/98366686/151093704-9e358f75-d4ce-4968-b735-35098a7275f5.png">

I am unable to upload an artist profile as an adimn.

**Comment by NFTPugs** [comment]
<img width="1272" alt="Screen Shot 2022-01-25 at 6 18 21 PM" src="https://user-images.githubusercontent.com/98366686/151107331-4894a7db-45d6-4f6b-80bb-65f8d9e4f346.png">

**Comment by rvmelkonian** [comment]
can you confirm that the audio type you were uploading was .mp3?

**Comment by NFTPugs** [comment]
It was a wav file.

**Comment by rvmelkonian** [comment]
cool, we haven't yet added an error message for this specific case, working on it now. Only mp3s and mp4s can be uploaded.

**Comment by rvmelkonian** [comment]
closing this now as we're working on tooltips in the modal to display accepted files types
