### ISSUE TITLE
Storybook / Next12 Error "https://storybook.js.org/blog/get-started-with-storybook-and-next-js/"

### ISSUE THREAD

**Issue by rvmelkonian** [INFLOWMusic/inflow-app#8]
Storybook shows the error 
``Image with src "static/media/components/common/Card/temp.jpeg" must use "width" and "height" properties or "layout='fill'" property.``

When previewing images in storybook. This seems to be because in Next.js 12 ``width`` and ``height`` are required fields.

**Comment by r29taheri** [comment]
I found a solution for it and it seems works fine:
`       width={6}
        height={4}
        objectFit="cover"
        layout="responsive"`

width={6} height={4} is ratio

**Comment by rvmelkonian** [comment]
correct, I just tried it for common/Card on the Next <Image /> and it renders fine. Closing this issue.
